
export const CREATE_AUTHOR = "CREATE_AUTHOR";
export const FETCH_AUTHORS = "FETCH_AUTHORS";
export const FETCH_AUTHOR = "FETCH_AUTHOR";
export const DELETE_AUTHOR = "DELETE_AUTHOR";
export const EDIT_AUTHOR = "EDIT_AUTHOR"
export const FETCH_AUTHORS_REQUESTED = "FETCH_AUTHORS_REQUESTED";
export const FETCH_AUTHORS_SUCCESS = "FETCH_AUTHORS_SUCCESS";
export const FETCH_AUTHORS_ERROR = "FETCH_AUTHORS_ERROR"